import { ReadonlyURLSearchParams } from "next/navigation";

// Generated by ai
// --- Helper Function untuk logic Ellipsis ---
export const generatePagination = (currentPage: number, totalPages: number) => {
  // Jika total halaman sedikit (<= 7), tampilkan semua
  if (totalPages <= 5) {
    return Array.from({ length: totalPages }, (_, i) => i + 1);
  }

  const siblingCount = 1; // Jumlah halaman tetangga di kiri/kanan halaman aktif
  const leftSiblingIndex = Math.max(currentPage - siblingCount, 1);
  const rightSiblingIndex = Math.min(currentPage + siblingCount, totalPages);

  // Cek apakah perlu menampilkan titik-titik
  const showLeftDots = leftSiblingIndex > 2;
  const showRightDots = rightSiblingIndex < totalPages - 1;

  // Case 1: Hanya titik di kanan (Posisi user di awal)
  if (!showLeftDots && showRightDots) {
    const leftItemCount = 3 + 2 * siblingCount;
    const leftRange = Array.from({ length: leftItemCount }, (_, i) => i + 1);
    return [...leftRange, "...", totalPages];
  }

  // Case 2: Hanya titik di kiri (Posisi user di akhir)
  if (showLeftDots && !showRightDots) {
    const rightItemCount = 3 + 2 * siblingCount;
    const rightRange = Array.from(
      { length: rightItemCount },
      (_, i) => totalPages - rightItemCount + i + 1,
    );
    return [1, "...", ...rightRange];
  }

  // Case 3: Titik di kiri dan kanan (Posisi user di tengah)
  if (showLeftDots && showRightDots) {
    const middleRange = Array.from(
      { length: rightSiblingIndex - leftSiblingIndex + 1 },
      (_, i) => leftSiblingIndex + i,
    );
    return [1, "...", ...middleRange, "...", totalPages];
  }

  return [];
};

export const createPageUrl = (
  newPage: number | string,
  searchParams: ReadonlyURLSearchParams,
  pathname: string,
) => {
  const params = new URLSearchParams(searchParams);
  params.set("page", newPage.toString());
  return `${pathname}?${params.toString()}`;
};
